#!/bin/bash
# 🌐 配置 oece.tech 自定義域名

echo "🌐 Setting up custom domain for oece.tech..."
echo ""

# 檢查 Firebase CLI
if ! command -v firebase &> /dev/null; then
    echo "❌ Firebase CLI not found. Installing..."
    npm install -g firebase-tools
fi

echo "📋 Step 1: 在 Firebase Console 添加域名"
echo ""
echo "請訪問以下 URL 並添加自定義域名："
echo "https://console.firebase.google.com/project/oece-tech-9aa8d/hosting/sites/oece-tech-9aa8d"
echo ""
echo "點擊 'Add custom domain' 並輸入: oece.tech"
echo ""
echo "Firebase 會給你 DNS 記錄，類似："
echo ""
echo "A 記錄:"
echo "  Type: A"
echo "  Name: @"
echo "  Value: 151.101.1.195"
echo ""
echo "  Type: A"
echo "  Name: @"
echo "  Value: 151.101.65.195"
echo ""
echo "CNAME 記錄:"
echo "  Type: CNAME"
echo "  Name: www"
echo "  Value: oece-tech-9aa8d.web.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Step 2: 在 .TECH Domains 配置 DNS"
echo ""
echo "1. 訪問: https://controlpanel.tech"
echo "2. 找到 oece.tech 域名"
echo "3. 點擊 'Manage' 或 DNS 設置"
echo "4. 添加上面的 A 記錄和 CNAME 記錄"
echo "5. 保存"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Step 3: 等待 DNS 生效"
echo ""
echo "通常需要 10-30 分鐘"
echo "檢查命令: dig oece.tech"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 配置完成後，訪問: https://oece.tech"
echo ""
