// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A headline generator AI agent.
 *
 * - generateHeadline - A function that handles the headline generation process.
 * - GenerateHeadlineInput - The input type for the generateHeadline function.
 * - GenerateHeadlineOutput - The return type for the generateHeadline function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateHeadlineInputSchema = z.object({
  businessType: z
    .string()
    .describe('The type of enterprise business, e.g., SaaS, e-commerce, finance, healthcare'),
  valueProposition: z
    .string()
    .describe(
      'The core value proposition of the cloud provider for enterprise businesses.'
    ),
});

export type GenerateHeadlineInput = z.infer<typeof GenerateHeadlineInputSchema>;

const GenerateHeadlineOutputSchema = z.object({
  headline: z.string().describe('A compelling headline for the landing page.'),
});

export type GenerateHeadlineOutput = z.infer<typeof GenerateHeadlineOutputSchema>;

export async function generateHeadline(input: GenerateHeadlineInput): Promise<GenerateHeadlineOutput> {
  return generateHeadlineFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateHeadlinePrompt',
  input: {schema: GenerateHeadlineInputSchema},
  output: {schema: GenerateHeadlineOutputSchema},
  prompt: `You are an expert marketing copywriter specializing in crafting compelling headlines for enterprise cloud providers.\n\n  Generate a single, attention-grabbing headline that highlights the value proposition for the given enterprise business type.\n\n  Business Type: {{{businessType}}}\n  Value Proposition: {{{valueProposition}}}\n\n  Headline:`,
});

const generateHeadlineFlow = ai.defineFlow(
  {
    name: 'generateHeadlineFlow',
    inputSchema: GenerateHeadlineInputSchema,
    outputSchema: GenerateHeadlineOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
